'use strict';

// Generator Module (ADR-008): a pure function, no DB/storage access. Turns
// AI-authored markdown into a real .pptx presentation: one title slide,
// then one slide per H1/H2 section, with paragraph lines turned into
// bullets and any embedded table rendered as a real pptxgenjs table.
// Reuses documentTheme.js's palette, matching markdownDocxGenerator.js/
// markdownPdfGenerator.js's own visual language.
//
// Deliberately simple slide-splitting: a new slide per H1/H2 (not H3 — H3
// content stays on its parent slide as a bold sub-heading bullet), each
// paragraph line becomes one bullet. This is a v1 "restructure prose into
// slides" pass, not a general summarization/slide-design engine — an
// AI-authored report already writes in short paragraphs/lists, so this
// mapping reads reasonably as slides without a second model call to
// re-summarize the content.
//
// image-size (a transitive dependency of pptxgenjs, used for image
// embedding) currently carries an unfixed high-severity DoS advisory
// (GHSA-w3rx-r6r6-pgpr / GHSA-5p2g-fcmc-qvqq) — flagged, accepted gap,
// same treatment excelGenerator.js's own uuid advisory already
// established in this codebase: this generator never embeds an image
// (only text/tables from markdown), so that parsing path is never
// exercised here.

const PptxGenJS = require('pptxgenjs');
const { parseTableAt } = require('./markdownTableParser');
const { HEX } = require('./documentTheme');

const MAX_BULLETS_PER_SLIDE = 8;

// One pass over the markdown, grouping content under each H1/H2 into a
// "slide" ({heading, bullets, table}) — an H3 becomes a bold bullet on the
// current slide rather than a slide of its own (three heading levels is
// one slide split too many for a short AI-authored report).
function splitIntoSections(markdown) {
  const lines = String(markdown || '').split(/\r?\n/);
  const sections = [];
  let current = null;
  const ensureCurrent = () => {
    if (!current) {
      current = { heading: null, bullets: [], table: null };
      sections.push(current);
    }
    return current;
  };

  let i = 0;
  while (i < lines.length) {
    const table = parseTableAt(lines, i);
    if (table) {
      ensureCurrent().table = table;
      i = table.endIndex;
      continue; // eslint-disable-line no-continue
    }

    const line = lines[i];
    const headingMatch = line.match(/^(#{1,3})\s+(.*)$/);
    if (headingMatch && headingMatch[1].length <= 2) {
      current = { heading: headingMatch[2], bullets: [], table: null };
      sections.push(current);
    } else if (headingMatch) {
      ensureCurrent().bullets.push({ text: headingMatch[2], bold: true });
    } else if (line.trim()) {
      ensureCurrent().bullets.push({ text: line.trim(), bold: false });
    }
    i += 1;
  }
  return sections;
}

function addContentSlide(pres, title, section) {
  const slide = pres.addSlide();
  slide.background = { color: HEX.paper };

  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 0,
    w: '100%',
    h: 0.9,
    fill: { color: HEX.accent },
    line: { type: 'none' },
  });
  slide.addText(title, {
    x: 0.4,
    y: 0,
    w: 9.2,
    h: 0.9,
    color: 'FFFFFF',
    bold: true,
    fontSize: 22,
    valign: 'middle',
  });

  const hasBullets = section.bullets.length > 0;
  if (hasBullets) {
    slide.addText(
      section.bullets.slice(0, MAX_BULLETS_PER_SLIDE).map((b) => ({
        text: b.text,
        options: {
          bullet: true,
          color: HEX.inkSoft,
          bold: b.bold,
          fontSize: b.bold ? 15 : 13.5,
          breakLine: true,
        },
      })),
      { x: 0.5, y: 1.15, w: 9, h: 3.3 },
    );
  }

  if (section.table) {
    const { columns, rows } = section.table;
    const tableRows = [
      columns.map((c) => ({
        text: c.label,
        options: { bold: true, color: 'FFFFFF', fill: { color: HEX.accent } },
      })),
      ...rows.map((row, i) =>
        columns.map((c) => ({
          text: row[c.id] === undefined || row[c.id] === null ? '' : String(row[c.id]),
          options: { fill: { color: i % 2 === 1 ? HEX.accentSoft : HEX.paper } },
        })),
      ),
    ];
    slide.addTable(tableRows, {
      x: 0.5,
      y: hasBullets ? 4.55 : 1.3,
      w: 9,
      fontSize: 11,
      border: { type: 'solid', color: HEX.line, pt: 0.5 },
    });
  }
}

async function generate({ title, markdown }) {
  const pres = new PptxGenJS();
  pres.defineLayout({ name: 'ARCNAVE_WIDE', width: 10, height: 5.63 });
  pres.layout = 'ARCNAVE_WIDE';

  const titleSlide = pres.addSlide();
  titleSlide.background = { color: HEX.accent };
  titleSlide.addText(title, {
    x: 0.6,
    y: 2.1,
    w: 8.8,
    h: 1.6,
    color: 'FFFFFF',
    bold: true,
    fontSize: 32,
    valign: 'middle',
  });
  titleSlide.addText('Generated by ARCNAVE', {
    x: 0.6,
    y: 3.7,
    w: 8.8,
    h: 0.5,
    color: HEX.paper,
    fontSize: 12,
  });

  const sections = splitIntoSections(markdown);
  sections.forEach((section) => addContentSlide(pres, section.heading || title, section));

  const output = await pres.write({ outputType: 'nodebuffer' });
  return Buffer.isBuffer(output) ? output : Buffer.from(output);
}

module.exports = { generate };
